name: Workflow Summary Builder
on:
  workflow_dispatch:

jobs:
  test-flow:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: npm install

    - name: run script
      uses: Prateek32177/GitSum@feat_action_core
